services:
  - type: web
    name: segundo-rey-web
    env: node
    plan: free
    buildCommand: |
      cd frontend && npm install && npm run build
    startCommand: |
      cd backend && npm install && node server.js
    envVars:
      - key: NODE_VERSION
        value: 22
      - key: EMAIL_FROM
        value: info@segundorey.com
      - key: EMAIL_PASS
        value: B4rc3lon4
      - key: LOGIN_USER
        value: catoira
      - key: LOGIN_PASS
        value: vikinga
      - key: FRONTEND_URL
        value: https://segundo-rey-web.onrender.com
      - key: DB_HOST
        value: jupiter.tropicalserver.net
      - key: DB_PORT
        value: 3306
      - key: DB_USER
        value: segundo_admin
      - key: DB_PASSWORD
        value: bbddsegundorey
      - key: DB_NAME
        value: segundo_segundorey
    autoDeploy: true
