services:
  - type: web
    name: segundo-rey-web
    env: node
    plan: free
    buildCommand: |
      cd frontend && npm install && npm run build
    startCommand: |
      cd backend && npm install && node server.js
    envVars:
      - key: NODE_VERSION
        value: 22
      - key: EMAIL_FROM
        value: info@demo.com
      - key: EMAIL_PASS
        value: una_clave_falsa_para_demo
      - key: LOGIN_USER
        value: demo
      - key: LOGIN_PASS
        value: 1234
      - key: FRONTEND_URL
        value: https://segundo-rey-web.onrender.com
      - key: DB_HOST
        value: jupiter.tropicalserver.net
       
    autoDeploy: true

